bin = './sord-mO'
cores = 2
dtype = '<f4'
email = 'yow004'
fortran_flags = {'O': ('-O3', '-fimplicit-none', '-Wall', '-o'), 'p': ('-O', '-pg', '-fimplicit-none', '-Wall', '-o'), 't': ('-fbounds-check', '-ffpe-trap=invalid,zero,overflow', '-fimplicit-none', '-Wall', '-o'), 'g': ('-fbounds-check', '-ffpe-trap=invalid,zero,overflow', '-g', '-fimplicit-none', '-Wall', '-o')}
fortran_mpi = ('mpif90',)
fortran_serial = ('gfortran',)
host = 'igpp13grad9-2.local'
hosts = ('igpp13grad9-2.local',)
infiles = ()
itbuff = 10
login = 'igpp13grad9-2.local'
machine = 'igpp13grad9-2.local'
maxcores = 2
maxnodes = 1
maxram = 8000000
maxtime = 0
mode = 'm'
name = 'flat-g'
nodes = 1
notes = '\nIGPP laptop\n\nssh -fNL localhost:8022:pisco.sdsu.edu:22 sciences.sdsu.edu\nssh -p 8022 localhost\n\nUse MPICH instead of OpenMPI:\nexport PATH="/opt/mpich2/gnu/bin:${PATH}"\n'
np = 4
optimize = 'O'
os_ = ('Darwin', 'igpp13grad9-2.local', '13.4.0', 'Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64', 'x86_64')
pmem = 33
post = ''
ppn = 4
pre = ''
prepare = True
queue = None
ram = 132
rate = 1000000.0
run = False
rundate = 'Thu Mar 26 23:55:37 2015'
rundir = '/Users/yow004/software/SORD/sord/scripts/flat-g'
totalcores = 2
user = 'yow004'
walltime = '0:12:00'
